name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 定义环境变量, 后面会使用
# 定义 APP_NAME 用于 docker build-args
# 定义 DOCKERHUB_REPO 标记 docker hub repo 名称
env:
  APP_NAME: symbolicator-centos
  DOCKERHUB_REPO: nttdocomoouyi/symbolicator-centos

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v2
        name: Login to DockerHub
        with:
          # GitHub Repo => Settings => Secrets 增加 docker hub 登录密钥信息
          # DOCKERHUB_USERNAME 是 docker hub 账号名.
          # DOCKERHUB_TOKEN: docker hub => Account Setting => Security 创建.
          username: nttdocomoouyi
          password: dckr_pat_g3hesdgX5-L6B-HzptBwJuH3Vpo
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:0.3.3
